#!/bin/bash
sudo yum update -y
sudo yum install httpd -y
sudo service httpd start
sudo chkconfig httpd on
sudo su
sudo echo "<html><body bgcolor="red"><h1> Hello World</h1></body><html>" > /var/www/html/index.html


#!/bin/bash
sudo yum install httpd -y
sudo yum update -y
sudo service httpd start
sudo chkconfig httpd on
sudo mkdir /var/www/html/test1
echo "<html><body bgcolor="red"><h1> Hello World from test1</h1></body><html>" > /var/www/html/test1/index.html


#!/bin/bash
sudo yum install httpd -y
sudo yum update -y
sudo service httpd start
sudo chkconfig httpd on
sudo mkdir /var/www/html/test2
echo "<html><body bgcolor="red"><h1> Hello World from test2</h1></body><html>" > /var/www/html/test2/index.html



###############################################################################################

#!/bin/bash
sudo yum install httpd -y
sudo yum update -y
sudo service httpd start
sudo chkconfig httpd on
sudo echo "<html><body bgcolor="red"><h1> Hello World</h1></body></html>" > /var/www/html/index.html


##################################################----Volume-Mount-----#########################
lsblk
file -s /dev/xvdf
sudo mkfs -t ext4 /dev/xvdf
sudo mkdir /newvolume
mount /dev/xvdf /newvolume/
cd /newvolume
df -h
