AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-0c02fb55956c7d316" # Amazon Linux 2
      SubnetId: !ImportValue PublicSubnetId
