AWSTemplateFormatVersion: '2010-09-09'
Description: Child Stack - Launches an EC2 Instance and references Security Group ID from the parent stack.

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

Mappings:
  RegionMap:
    us-east-1:
      t2micro: ami-0c55b159cbfafe1f0
      t2small: ami-0c55b159cbfafe1f0
      t2medium: ami-0c55b159cbfafe1f0

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - !FindInMap
          - InstanceTypeMap
          - !Ref InstanceType
          - KeyName
      SecurityGroupIds:
        - !ImportValue MyNetworkStack-SecurityGroupId
      KeyName: my-key-pair
      Tags:
        - Key: Name
          Value: CrossStack-EC2Instance     

        
Outputs:
  EC2InstanceId:
    Description: The ID of the created EC2 instance
    Value: !Ref MyEC2Instance
  
